# Generated by Django 3.0.3 on 2020-08-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewLanguage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='brief_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Brief Description'),
        ),
    ]
