# Generated by Django 3.0.3 on 2020-08-26 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewLanguage', '0002_language_brief_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='language',
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NewLanguage.Stage'),
        ),
    ]
