# Generated by Django 3.0.3 on 2020-08-27 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewLanguage', '0003_auto_20200826_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NewLanguage.Language'),
            preserve_default=False,
        ),
    ]
